name: 'Replace Tokens'
description: 'Read environment variables and replace tokens in a YAML file'
inputs:
  input-yaml-file:
    description: 'Path to the YAML file'
    required: true
  output-yaml-file:
    description: 'Path to the output YAML file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_YAML_FILE: ${{ inputs.input-yaml-file }}
    OUTPUT_YAML_FILE: ${{ inputs.output-yaml-file }}